services:
  - type: web
    name: wans-collection-inventory
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: APP_PASSWORD
        value: wans123
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: wans-db
          property: connectionString

databases:
  - name: wans-db
    databaseName: wans_inventory
    plan: free
